export const CATEGORY_CREATED = "CATEGORY_CREATED";
export const CATEGORY_CREATION_FAIL = "CATEGORY_CREATION_FAIL";
export const GET_CATEGORIES = "GET_CATEGORIES";
export const GET_CATEGORIES_FAIL = "GET_CATEGORIES_FAIL";
export const CATEGORY_CREATED_REDIRECTED = "CATEGORY_CREATED_REDIRECTED";