export const GET_USERS_ERROR = "GET_USERS_ERROR";
export const GET_USERS = "GET_USERS";
export const DELETE_USER_ERROR = "DELETE_USER_ERROR";
export const DELETE_USER = "DELETE_USER";
export const SET_USER_ROLE = "SET_USER_ROLE";
export const SET_USER_ROLE_ERROR = "SET_USER_ROLE_ERROR";
export const SET_ROLE_REDIRECTED = "SET_ROLE_REDIRECTED";
